openapi: 3.0.0
info:
    version: 1.0.0
    title: ecommerce
security:
    - bearerAuth: []

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        MongoDBObjectId:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
            description: >
                Identificador único de un documento en MongoDB.
                Debe ser una cadena hexadecimal de 24 caracteres.
        Product:
            type: object
            properties:
                _id:
                    $ref: '#/components/schemas/MongoDBObjectId'
                title:
                    type: string
                    description: Título del producto
                    minLength: 1
                description:
                    type: string
                    description: Descripción del producto
                    minLength: 1
                code:
                    type: string
                    description: Código del producto (único)
                    minLength: 1
                    uniqueItems: true
                price:
                    type: number
                    description: Precio del producto
                status:
                    type: boolean
                    description: Estado del producto (opcional por defecto true)
                stock:
                    type: number
                    description: Cantidad en stock del producto
                category:
                    type: string
                    description: Categoría del producto
                    minLength: 1
                thumbnails:
                    type: array
                    items:
                        type: string
                    description: Lista de URLs de miniaturas (opcional por defecto [])
                owner:
                    type: string
                    description: Hace referencia al email del usuario owner (opcional por defecto 'admin')
    examples:
        ProductFindOne:
            value:
                status: success
                message: Product found successful
                data:
                    owner: admin
                    _id: 649227cc84cf9a8cc6ce5fe0
                    title: Sausages
                    description: The automobile layout consists of a front-engine design with transaxle-type transmissions mounted at the rear of the engine and four wheel drive
                    code: abc81
                    price: 13
                    status: true
                    stock: 92
                    category: Unbranded
                    thumbnails: []
                    __v: 0

paths:
    /products/mockingproducts:
        get:
            summary: Obtiene productos de prueba.
            tags: [Products]
            security:
                - bearerAuth: []
            responses:
                200:
                    description: Productos obtenidos exitosamente.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        description: Estado de la respuesta (success, error, etc.)
                                    payload:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                _id:
                                                    type: string
                                                    description: Identificador único del producto
                                                title:
                                                    type: string
                                                    description: Título del producto
                                                description:
                                                    type: string
                                                    description: Descripción del producto
                                                code:
                                                    type: string
                                                    description: Código del producto
                                                price:
                                                    type: string
                                                    description: Precio del producto
                                                status:
                                                    type: boolean
                                                    description: Estado del producto (true o false)
                                                stock:
                                                    type: integer
                                                    description: Cantidad en stock del producto
                                                category:
                                                    type: string
                                                    description: Categoría del producto
                                                thumbnails:
                                                    type: array
                                                    items:
                                                        type: string
                                                        description: URL de la miniatura del producto
                401:
                    description: No autorizado.
                403:
                    description: Forbidden.

    /products/{pid}:
        get:
            summary: Obtiene un producto por ID.
            tags: [Products]
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: pid
                  required: true
                  description: ID del producto a obtener.
                  schema:
                      type: string
            responses:
                201:
                    description: Producto agregado exitosamente.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        description: Estado de la respuesta (success, error, etc.)
                                    message:
                                        type: string
                                        description: Mensaje descriptivo de la respuesta
                                    data:
                                        type: object
                                        properties:
                                            title:
                                                type: string
                                                description: Título del producto
                                            description:
                                                type: string
                                                description: Descripción del producto
                                            code:
                                                type: string
                                                description: Código del producto
                                            price:
                                                type: number
                                                description: Precio del producto
                                            status:
                                                type: boolean
                                                description: Estado del producto (puede ser nulo)
                                            stock:
                                                type: integer
                                                description: Cantidad en stock del producto
                                            category:
                                                type: string
                                                description: Categoría del producto
                                            thumbnails:
                                                type: array
                                                description: Lista de miniaturas del producto (puede ser nulo)
                                                items:
                                                    type: string
                                            owner:
                                                type: string
                                                description: Propietario del producto
                                            _id:
                                                type: string
                                                description: Identificador único del producto
                                            __v:
                                                type: integer
                                                description: Versión del esquema
                401:
                    description: No autorizado.
                403:
                    description: Forbidden.
